### ISSUE TITLE
NoClassDefFoundError: org/mule/weave/v2/io/service/WorkingDirectoryService

### ISSUE THREAD

**Issue by ca-stefan-cordes** [rbutenuth/data-weave-caller#2]
```
java.lang.NoClassDefFoundError: org/mule/weave/v2/io/service/WorkingDirectoryService
	at de.codecentric.dwcaller.utils.WeaveRunnerBuilder.createServiceManager(WeaveRunnerBuilder.java:111)
	at de.codecentric.dwcaller.utils.WeaveRunnerBuilder.build(WeaveRunnerBuilder.java:78)
	at de.codecentric.dwcaller.TestRunner.runTests(TestRunner.java:76)
	at de.codecentric.dwcaller.TestRunner.run(TestRunner.java:64)
	at de.codecentric.dwcaller.test.DataWeaveTests.some(DataWeaveTests.java:38)
	at com.canda.dataweave.CallDataWeaveTests.dataWeaveTests(CallDataWeaveTests.java:13)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: java.lang.ClassNotFoundException: org.mule.weave.v2.io.service.WorkingDirectoryService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more


```

**Comment by ca-stefan-cordes** [comment]
WorkingDirectoryService was taken from pre-SNAPSHOT version 2.6.0-20230609 but in the final version it was moved to 
org.mule.weave.v2.**core**.io.service.WorkingDirectoryService

**Comment by rbutenuth** [comment]
Should be solved with release 1.2.0 (or earlier)
